draw_config:
  key_w: 60.0
  key_h: 61.0
  combo_w: 20.0
  combo_h: 30.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 2.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 6
    rel_w: 6
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: "svg.keymap { font-family: 'JetBrains Mono'; }"
  footer_text: ""
  shrink_wide_legends: 5
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  zmk_additional_includes:
    - "zmk-helpers/include"
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    {
      "&capsdance": "$$mdi:apple-keyboard-caps$$",
      "&caps_word": "CAPSWORD",
      "&bt BT_SEL 0": { t: "bt 0" },
      "&bt BT_SEL 1": { t: "bt 1" },
      "&bt BT_SEL 2": { t: "bt 2" },
      "&bt BT_SEL 3": { t: "bt 3" },
      "&bt BT_SEL 4": { t: "bt 4" },
      "&hmr RGUI K": { t: "K", h: "Gui" },
      "&hmr RCTRL L": { t: "L", h: "Ctrl" },
      "&hmr RALT SEMI": { t: ";", h: "Alt", s: ":" },
      "&hmr RSHIFT J": { t: "J", h: "Shift" },
      "&hml LGUI D": { t: "D", h: "Gui" },
      "&hml LCTRL S": { t: "S", h: "Ctrl" },
      "&hml LALT A": { t: "A", h: "Alt" },
      "&hml LSHIFT F": { t: "F", h: "Shift" },
      "&lpar": { t: "(" },
      "&rpar": { t: ")" },
    }
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ""
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: ^
    right_ctrl: ^
    left_shift: ⇧
    right_shift: ⇧
    left_alt: ⎇
    right_alt: ⎇
    left_gui: ⌘
    right_gui: ⌘
    keycode_combiner: "{mods}+{key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
    - KC_
  qmk_keycode_map:
    XXXXXXX: ""
    "NO": ""
    MINUS: "-"
    MINS: "-"
    EQUAL: "="
    EQL: "="
    LEFT_BRACKET: "["
    LBRC: "["
    RIGHT_BRACKET: "]"
    RBRC: "]"
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: "#"
    NUHS: "#"
    SEMICOLON: ;
    SCLN: ;
    QUOTE: "'"
    QUOT: "'"
    GRAVE: "`"
    GRV: "`"
    COMMA: ","
    COMM: ","
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: "~"
    TILD: "~"
    EXCLAIM: "!"
    EXLM: "!"
    AT: "@"
    HASH: "#"
    DOLLAR: $
    DLR: $
    PERCENT: "%"
    PERC: "%"
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: "&"
    AMPR: "&"
    ASTERISK: "*"
    ASTR: "*"
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: "{"
    LCBR: "{"
    RIGHT_CURLY_BRACE: "}"
    RCBR: "}"
    PIPE: "|"
    COLON: ":"
    COLN: ":"
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: ">"
    RABK: ">"
    GT: ">"
    QUESTION: "?"
    QUES: "?"
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: "\\"
    BSLH: "\\"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: "."
    DOT: "."
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
    LCTRL: Ctrl
    RCTRL: Ctrl
    LSHIFT: Shift
    RSHIFT: Shift
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    DEL: ⌦
    BACKSPACE: ⌫
    RET: ⮐
    ESC: "$$mdi:location-exit$$"
    TAB: ⇥
    N1:
      s: "!"
      t: "1"
    N2:
      s: "@"
      t: 2
    N3:
      s: "#"
      t: 3
    N4:
      s: "$"
      t: 4
    N5:
      s: "%"
      t: 5
    N6:
      s: "^"
      t: 6
    N7:
      s: "&"
      t: 7
    N8:
      s: "*"
      t: 8
    N9:
      s: (
      t: 9
    N0:
      s: ")"
      t: "0"
    KP_N1: "1"
    KP_N2: "2"
    KP_N3: "3"
    KP_N4: "4"
    KP_N5: "5"
    KP_N6: "6"
    KP_N7: "7"
    KP_N8: "8"
    KP_N9: "9"
    KP_N0: "0"
    SPACE: ␣
    C_VOLUME_UP: "$$mdi:volume-plus$$"
    C_VOLUME_DOWN: "$$mdi:volume-minus$$"
    C_MUTE: "$$mdi:volume-off$$"
    C_NEXT: "$$mdi:skip-next$$"
    C_PREV: "$$mdi:skip-previous$$"
    C_PLAY_PAUSE: "$$mdi:play-pause$$"
    LEFT: "$$mdi:arrow-left$$"
    UP: "$$mdi:arrow-up$$"
    DOWN: "$$mdi:arrow-down$$"
    RIGHT: "$$mdi:arrow-right$$"
  zmk_combos:
    {
      "combo_capsword":
        { "align": "top", "offset": 0.25, width: 80.0, height: 20.0 },
      "combo_capslock":
        { "align": "top", "offset": 0.95, width: 60.0, height: 20.0 },
      "combo_s_all": { "align": "top", "offset": 0.3 },
      "combo_cut": { "align": "bottom", "offset": 0 },
    }
